### PR TITLE
added activeTab as prob for setting tabIndex

### PR DESCRIPTION
**Pull request by kperveen**
Right now, the active tab is set on click, this adds a prop to let the parent component set the activeIndex from its side.

### CODE REVIEW

**Comment by TerryZ** [comment]
Why parent component need to switch SelectMenu menu group tab?

**Comment by kperveen** [comment]
The component shows the tab that was last active when you open it again after closing it regardless of the value that is already selected

**Comment by kperveen** [comment]
@TerryZ any update on this?

**Comment by TerryZ** [comment]
Sorry for so late to merge, thanks for your PR.

**Pull request merged**
